spring:
  profiles:
    active: local

cloud:
  aws:
    stack:
      auto: false
    region:
        static: us-east-1
    sqs:
      url: ${SQS_URL}
      region: {REGION}
      name: ${QUEUE_NAME}
      maxMsgToRead: 10
      assume-role:
        roleArn: ${ROLE_ARN}
        durationSeconds: 3600 # 1 hr is the max session length allowed for local dev.
        roleSessionName: sqs-agg-spike-session
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error